public without sharing class PartnerSignupFormConstants {
    
    public static final String TYPE = 'Partner';
    public static final String PERSON_ACC_REC_TYPE_NAME = 'Individual_Partner';
    public static final String COMPANY_NOT_FOUND = 'Company Not Found with this Name and Website';
    public static final String SUCCESS_MESSAGE = 'Success';
    public static final String FAILED_MESSAGE = 'Failed';
    public static final String GST = 'gstPdf';
    public static final String PAN = 'panPdf';
    public static final String COMP_CERT = 'comCertPdf';
    public static final String CAN_CHEQUE = 'canChePdf';
    public static final String GST_TITLE = 'GST Certificate Document';
    public static final String PAN_TITLE = 'PAN Card Copy';
    public static final String COMP_CERT_TITLE = 'Company Certification Copy';
    public static final String CAN_CHEQUE_TITLE = 'Company Cancelled Cheque Copy';
    public static final String CON_EXTERNAL_REC_TYPE = 'External';
    public static final String CONTACT_TITLE = 'Resource';
    public static final String FOUND = 'Found';
    public static final String NOT_FOUND = 'Not Found';
    public static final String ADMIN_EMAIL_SUBJECT = 'Successful Partner Onboarding Process Details and Document Verification';
    public static final String PROFILE_NAME_SYSTEM_ADMIN = 'System Administrator';

}