public class ZohoSignConstants {
    
     public static final String METHOD_TYPE_POST = 'POST';
    
     public static final String REFRESH_TOKEN = '&refresh_token=';
    
     public static final String GRANT_TYPE = '&grant_type=';
    
     public static final String CLIENT_ID = 'client_id=';
    
     public static final String CLIENT_SECRET = '&client_secret=';
    
     public static final String REDIRECT_URI = '&redirect_uri=';
    
     public static final String ACCESS_TOKEN = 'access_token';
    
     public static final String IS_QUICK_SEND = 'is_quicksend';
    
     public static final String DATA = 'data';
     
     public static final String REQUEST_HEADER_AUTHORIZATION = 'Authorization';
    
     public static final String REQUEST_HEADER_CONTENT_TYPE = 'Content-Type';
    
     public static final String REQUEST_HEADER_AUTHORIZATION_TYPE = 'Zoho-oauthtoken';
    
     public static final String REQUEST_HEADER_CONTENT_TYPE_APPLICATION_JSON = 'application/x-www-form-urlencoded'; 

}